---
      - name: run apt-get on the server
        apt:
          update_cache: yes

      - name: Install {{package}}
        apt:
          name: "{{package}}"
          state: present

      - name: copy data files into apache
        template:
          src: ../templates/index.html.j2
          dest: /var/www/html/index.html
        register: copy_status
        notify: restart apache

